# Generated by Django 5.1.6 on 2025-02-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ads",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="ads.user",
            ),
        ),
    ]
