# Generated by Django 5.1.6 on 2025-02-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ads_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="contact_info",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
