# Generated by Django 5.1.6 on 2025-03-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_ads_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="contact_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
